export const projects = [
  {
    id: 8,
    name: "Vision Glasses",
    description:
      "Smart vision glasses designed for the blind, aimed at environment recognition and real-time guidance.",
    github: "https://github.com/Parth17/vision-glasses",
    live: "https://vision-glasses.vercel.app/",
    tag: "Python, TensorFlow, OpenCV, Embedded Systems",
    image: "vision-glasses.png",
    createdOn: "2024",
    additionalTags: ["Machine Learning", "Deep Learning", "AI"],
  },
  // {
  //   id: 7,
  //   name: "Tail track",
  //   description:
  //     "Track your custom events easily and quickly. Also, get notifications on Slack via webhook.",
  //   github: "https://github.com/Parth17/tail-track",
  //   live: "https://tail-track.vercel.app?ref=portfolio",
  //   tag: "Next, Tailwind, Typescript, Next auth, Redis, PostgreSQL, Shadcn",
  //   image: "tail-track.png",
  //   createdOn: "2024",
  //   additionalTags: ["New"],
  // },
  // {
  //   id: 6,
  //   name: "NPM counter",
  //   description: "Get count of any npm package quickly!",
  //   github: "https://github.com/Parth17/npmcounter",
  //   live: "https://npmcounter.vercel.app/",
  //   tag: "Next, Tailwind, Typescript",
  //   image: "npm.png",
  //   createdOn: "2024",
  //   additionalTags: ["New"],
  // },
  // {
  //   id: 5,
  //   name: "Dev Planet Blog",
  //   description:
  //     "Collaborate with Team with team collab. Assign and monitor tasks and share files with the team.",
  //   github: "https://github.com/Parth17/planet-blog",
  //   live: "https://planet-blog.vercel.app/",
  //   tag: "Next, Tailwind, Typescript, Next auth, Contentlayer, MDX",
  //   image: "blog.png",
  //   createdOn: "2023",
  //   additionalTags: ["New"],
  // },
  {
    id: 4,
    name: "AI Research Assistant",
    description:
      "A system that allows users to ask natural language questions about research papers and geospatial data, providing insights and maps based on the input.",
    github: "https://github.com/Parth17/ai-research-assistant",
    live: "https://ai-research-assistant.vercel.app/",
    tag: "Python, Transformers, RAG, BERT, GIS",
    image: "ai-research-assistant.png",
    createdOn: "2023",
    additionalTags: ["GenAI", "Deep Learning"],
  },
  {
    id: 3,
    name: "Url Shortener",
    description:
      "Mock website for a URL shortener service. Used shrtco.de's API to shorten the given URL and persisted in the local storage.",
    github: "https://github.com/Parth17/Shortly",
    live: "https://shortlytif.netlify.app/",
    tag: "React",
    image: "url.png",
    createdOn: "2019",
  },
  // {
  //   id: 2,
  //   name: "CDF (CLI)",
  //   description:
  //     "Generate files with boilerplate code, for competitive programmers. 1000+ Downloads on NPM.",
  //   github: "https://github.com/Parth17/dirMaker",
  //   live: "https://www.npmjs.com/package/@Parth17/cdf",
  //   tag: "Node, CLI",
  //   image: "cdn.png",
  //   createdOn: "2020",
  // },
  {
    id: 1,
    name: "Team Collab",
    description:
      "Collaborate with Team with team collab. Assign and monitor tasks and share files with the team.",
    github: "https://github.com/Parth17/teams-frontend-v2",
    live: "https://teams-frontend.vercel.app/",
    tag: "Next, Tailwind, Node, MongoDB, Express",
    image: "team-collab.png",
    createdOn: "2023",
  },
];
